package.json

Currently the master branch is broken unless you roll back to commit d21731e, install and then roll forwards.  Travis CI has been failing since this build https://travis-ci.org/gruntjs/grunt-contrib-jasmine/builds/49943050
The problems are caused by the version bump on grunt-lib-phantomjs and jasmine-core so I've rolled back just those versions and left the rest as it is on master.
To test this fix I've been running `rm -Rf node_modules/ && npm install && npm test` which fails on master and works on this fork/branch/PR.

Rolling back dependencies to stabilise the build.

---

tasks/jasmine.js

With [`options.summary`](https://github.com/gruntjs/grunt-contrib-jasmine/tree/v0.9.0#optionssummary) set to `true`, this fatal error occurs:
```
Summary (1 tests failed)
Fatal error: Cannot read property 'display' of undefined
```
This bug was [introduced](https://github.com/gruntjs/grunt-contrib-jasmine/commit/f5ac86edf27d0eb9cca1bbba910026f532219bbe#diff-4c8c01561530ef0c744c24ba18bf03b1R381) in commit f5ac86e ("Assorted lint fixes") on 23 April 2015. The first affected version is [v0.9.0](https://github.com/gruntjs/grunt-contrib-jasmine/releases/tag/v0.9.0).

Fix bug in logSummary()

---

tasks/lib/jasmine.js

Removed install dependent path resolution.  The assumption of the package structure limits the usage of this module to only vanilla node.js when it doesn't have to.  By using dynamic resolution other structures may be utilized as well as allowing for the default structure to change without breaking implementation.

Remove install dependent path resolution.

---

tasks/lib/jasmine.js

Utilizing change from https://github.com/gruntjs/grunt-contrib-jasmine/pull/224, just fixing whitespace error to get PR merged.

Fix path resolution of es5shim

---

package.json

:tada: PhantomJS 2.1.1  :tada:
https://github.com/gruntjs/grunt-lib-phantomjs/pull/96
https://github.com/Medium/phantomjs/pull/439

bump grunt-lib-phantomjs to 1.0.0 (updates phantomjs to 2.1.1)

---

README.md
tasks/jasmine.js
tasks/lib/jasmine.js

I had a need to [customise Jasmine's boot file](http://jasmine.github.io/2.3/custom_boot.html), but I discovered that the path of the file is [hard-coded to `.grunt/grunt-contrib-jasmine/boot.js`](https://github.com/gruntjs/grunt-contrib-jasmine/blob/v0.9.0/tasks/lib/jasmine.js#L100) which is a copy of `node_modules/jasmine-core/lib/jasmine-core/boot.js`.
Here's one solution: a new `customBootFile` option. I've found it useful, and thought it would be worth submitting a PR. What do you think?

Add new option: customBootFile

---

package.json
tasks/lib/jasmine.js

PhantomJS 2.x is already ES5 compliant, so no need
to include `es5-shim` anymore.

Stop including `es5-shim`

---

Gruntfile.js
README.md
docs/jasmine-examples.md
docs/jasmine-options.md
tasks/jasmine.js
tasks/jasmine/templates/DefaultRunner.tmpl
tasks/lib/jasmine.js
test/fixtures/custom-temp-dir/spec/test-spec.js
test/fixtures/custom-temp-dir/src/test.js
test/jasmine_test.js

Fixes #60 and #170.
- Adds the `tempDir` option to the grunt config, and defaults to the original value `.grunt/grunt-contrib-jasmine`.
- Only tries to delete the `.grunt` folder, but not the parents of a custom temp directory.
- Adds the `favicon` path to the template context to keep the logic for joining paths out of the template.
- Adds a test that uses a custom temp directory
- Ensures the runner was loaded
- Checks that the jasmine resources are being loaded from the custom directory
- Documents the `tempDir` option
- Provides an example
- Updates the readme with the new documentation

Custom temp directory

---

package.json

Jasmine-core's newest minor version, 2.5.0, is causing tests to break. The previous release was 2.4.1. In package.json, I set the version to `~2.4.0`.

fix(dependencies): Prevent npm from installing jasmine@2.5.0

---

tasks/jasmine.js

Starting in Node.js v7.0.0, omitting the callback to async functions
emits a deprecation warning. Update the call to `fs.unlink` to instead
use `fs.unlinkSync`, which does not expect a callback.

Fix deprecation warning in Node.js 7

---

.gitignore
Gruntfile.js
docs/jasmine-options.md
package-lock.json
package.json
tasks/jasmine.js
tasks/lib/jasmine.js
test/fixtures/versions/spec/SpecVersion25.js
test/fixtures/versions/spec/SpecVersion31.js

Added the npm module, `pakote`, to download the jasmine version supplied in `options.version`.
We check out `jasmine-core` into `node_modules/grunt-contrib-jasmine/.jasmine` so that it's not downloaded every time you run the task and so that user doesn't have to modify their `.gitignore` file.
Added `latest` as a possible value with the caveat that it will not be updated once the task has downloaded it.
This has the potential to break existing tests because of the default value of `latest` which will upgrade the jasmine version to `3.1.0` at the moment. This should be doc-ed in the release notes.
Closes #260
Closes #263
Closes #250
Closes #230
Co-Authored-By: steveoh <sgourley@utah.gov>

Implement options.version

---

tasks/jasmine.js

Rather then using `__dirname` (which is the directory of the current file) we use the current working directory of the process to find the spec runner file.

Deals with #274

---

README.md
tasks/jasmine.js

- create new optional 'noSandbox' option to launch Puppeteer with --no-sandbox argument. It solves Debian Puppeteer launch issue (https://github.com/Googlechrome/puppeteer/issues/290)
- write down the doc

Create new optional 'noSandbox' option.

---

tasks/jasmine.js
tasks/lib/jasmine.js

When you are running tests the first time, you might encounter the following error. It's because we didn't wait for jasmine installation to finish before launching chrome.
```
function bold() { [native code] }
>> Error caught from Puppeteer
Warning: Error: net::ERR_FILE_NOT_FOUND at file:///_SpecRunner.html
at navigate (/node_modules/puppeteer/lib/Page.js:539:37)
at <anonymous>:null:null
at process._tickCallback (internal/process/next_tick.js:188:7)
Use --force to continue.
```

Fix the timing issue between installing jasmine and launching headless chrome

---

tasks/jasmine.js

Before this PR, when you ran the task as build only, it failed every time.

fix: build only should pass if the buildSpecrunner runs without error

---

package-lock.json
package.json

`>= 1.13.0` of `puppeteer` is required due to a [vulnerability](https://www.npmjs.com/advisories/824)

update puppeteer version

---

Gruntfile.js
package-lock.json
package.json
tasks/jasmine.js
tasks/jasmine/reporters/PuppeteerReporter.js
tasks/lib/jasmine.js
test/fixtures/customTemplateProcessor/template.js
test/fixtures/customTemplateProcessor/template.tmpl
test/jasmine_test.js

A small refactor to support feature mentioned in issue #281. Also bumped the version of grunt as `npm audit` was complaining about vulnerabilities.
This PR introduces a node native `EventEmitter` to handle all events being sent out of the puppeteer sandbox (instead of the previous exposeFunction based system) and exposes it to custom templates during the `buildSpecRunner` step. I tried to make as few changes as possible.
This allows a custom template to bind event handlers and receive custom messages (as well as `jasmine.*` messages) from within the puppeteer sandbox.
An example of such a template is included as part of a new test case, though the test case needs work to actually test that it is working as expected.

Introduce a proper event dispatcher for sandbox communication

---

README.md
tasks/jasmine.js

Fixes #307
Submitting this PR for the sandboxArgs feature. In my use case I need to use a different version of chrome then what's provided with Puppeteer.
I use this to leverage the `executeablePath` argument.

Option for sandboxArgs; passing options to puppeteer

---

tasks/jasmine.js

This PR relates to [issue 299](https://github.com/gruntjs/grunt-contrib-jasmine/issues/299)
Upon further inspection I noticed that the function that is awaited until the jasmine tests complete is defined closer to the top of the file where I don't believe it is getting properly reset between multi tasks, causing the strange behavior I observed. 
I've simply moved that function definition into the `launchPuppeteer` function and explicitly pass it into the `setup` function, and this seems to fix the issue.

moved resolveJasmine/jasminePromise function to fix scope issue

---

.travis.yml
appveyor.yml
package-lock.json
package.json

Recently we encountered an error from Chromium after upgrading Mac to 11.3.1. This issue can be resolved after upgrading to newer puppeteer which will use new version of Chromium.
```
Error caught from Headless Chrome. More info can be found by opening the Spec Runner in a browser.
>> Error: Page crashed!
>>   at Page._onTargetCrashed (/Users/fred/project/node_modules/puppeteer/lib/Page.js:215:24)
>>   at CDPSession.<anonymous> (/Users/fred/project/node_modules/puppeteer/lib/Page.js:123:56)
>>   at CDPSession.emit (events.js:315:20)
>>   at CDPSession._onMessage (/Users/fred/project/node_modules/puppeteer/lib/Connection.js:200:12)
>>   at Connection._onMessage (/Users/fred/project/node_modules/puppeteer/lib/Connection.js:112:17)
>>   at WebSocket.<anonymous> …
```

bump puppeteer to 8.0.0
